#!/bin/sh

mkdir -p /home/chris11/projects/def-stbil30/chris11/20240318_CnR_batch2/output/cnr-pipeline_batch2-GRCh38_PE/tracks_byReplicate

sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_HeLa_AR_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_HeLa_H3K4me3_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_HeLa_IgG_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_MCF7_ER_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_MCF7_IgG_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_AR_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_AR_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_AR_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_AR_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_ER_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_ER_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_ER_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_ER_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_H3K4me3_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_IgG_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_IgG_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_IgG_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/09_bamToBigwig/batch_sh/bamToBigwig_VCaP_IgG_R1881_rep1.sh