#!/bin/sh

sbatch scripts/CnR_JAZF1_pipeline/06_sambamba_markdup/batch_sh/sambamba_markdup_K562_JAZF1_rep1.sh
sbatch scripts/CnR_JAZF1_pipeline/06_sambamba_markdup/batch_sh/sambamba_markdup_K562_JAZF1_rep2.sh
sbatch scripts/CnR_JAZF1_pipeline/06_sambamba_markdup/batch_sh/sambamba_markdup_K562_IgG_rep1.sh
sbatch scripts/CnR_JAZF1_pipeline/06_sambamba_markdup/batch_sh/sambamba_markdup_K562_IgG_rep2.sh