#!/bin/sh

sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_AR_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_H3K4me3_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_HeLa_IgG_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_MCF7_ER_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_MCF7_IgG_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_AR_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_AR_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_AR_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_AR_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_ER_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_ER_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_ER_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_ER_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_H3K4me3_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_IgG_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_IgG_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_IgG_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/07_sambamba_view_filter/batch_sh/sambamba_view_filter_VCaP_IgG_R1881_rep1.sh