#!/bin/sh

sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_HeLa_AR_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_HeLa_H3K4me3_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_HeLa_IgG_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_MCF7_ER_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_MCF7_IgG_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_AR_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_AR_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_AR_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_AR_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_ER_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_ER_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_ER_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_ER_R1881_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_H3K4me3_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_IgG_EtOH_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_IgG_E2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_IgG_R1881xE2_rep1.sh
sbatch scripts/CnR_batch2_pipeline/08_sambamba_flagstat/batch_sh/sambamba_flagstat_VCaP_IgG_R1881_rep1.sh